### ISSUE TITLE
A Project & Product Mgmt Platform

### ISSUE THREAD

**Issue by buzzaz** [pAI-OS/paios#28]
ISSUE / PROBLEM / USER STORY: WHO, WHAT, WHY.
ISSUE / PROBLEM RESOLUTION: HOW

As a project or product manager, I want to be able to manage my backlog and the work that's being done on the backlog, and ensure that the work on each item is in a visible 
[NOTE: ABOVE ASK HAS 2 "WHAT" REQUIREMENTS. NEED TO SEPARATE.]

Narrative: 
<AZ to edit and enter a detailed description before clicking "Submit new issie">

Acceptance Criteria:
-Manage backlog
-Manage work in progress
-Be able to declare priority and move items when priorities shift 
-Be able to sort inquiries by difficulty, or by precedence in the order in which they will be required

Additional Backlog Items Created by Research into this item:
-Local vs Network resource inquiries (Nicole will create this user story / backlog item)

**Comment by samj** [comment]
Org-level product management project created (https://github.com/orgs/pAI-OS/projects/7) and invite sent to @buzzaz
